src/main/java/com/nighthawk/spring_portfolio/mvc/bathroom/BathroomQueueApiController.java

comments for API controller

---

src/main/resources/templates/assignments/assignment_tracker.html

Accidentally deleted function in JS for processing grading by teacher. Re-adding back to allow for full functinoality.

readding grade submissions function bc I accidentally deleted

---

src/main/java/com/nighthawk/spring_portfolio/mvc/Slack/SlackController.java

Reverts CSA-Coders-2025/CSA_Combined_Backend_Fork#46

Revert "slack integration repair"

---

src/main/java/com/nighthawk/spring_portfolio/mvc/Slack/SlackController.java

Reverts CSA-Coders-2025/CSA_Combined_Backend_Fork#47

Revert "Revert "slack integration repair""

---

src/main/resources/templates/assignments/assignment_tracker.html

Roles is currently broken, and it checks to see if student has a role.
To allow for the MVP of teacher toolkit to work, remove check to see if role is a student, so team teachers can grade the assignments.
Will later be fixed once roles are fixed with the login.

removed role_student call bc it roles is currently broken

---

src/main/java/com/nighthawk/spring_portfolio/mvc/student/StudentInfo.java
src/main/java/com/nighthawk/spring_portfolio/mvc/student/StudentInfoApiController.java
src/main/resources/templates/assignments/assignment_tracker.html
src/main/resources/templates/layouts/nav.html
src/main/resources/templates/student/table-details.html
src/main/resources/templates/student/tables_per3.html

Connected Kayden's student comments feature to teacher page on backend

Integrated Student Comments into Teacher Grading Page

---

src/main/java/com/nighthawk/spring_portfolio/mvc/dice/DiceApiController.java
src/main/java/com/nighthawk/spring_portfolio/mvc/mines/MinesApiController.java
src/main/java/com/nighthawk/spring_portfolio/mvc/poker/PokerApiController.java

- changed from using email to uid

Casinobranch

---

src/main/java/com/nighthawk/spring_portfolio/mvc/cryptoMining/MiningController.java
src/main/java/com/nighthawk/spring_portfolio/mvc/cryptoMining/MiningUserRepository.java
src/main/java/com/nighthawk/spring_portfolio/mvc/cryptoMining/TestMiningService.java

- Making the GPU Inventory is shown at the bottom
- Successfully had the crypto-mining running ( but still need time to see if the mining logic is working or no)
---
- Still need to get the activate/deactivate button to be working in the GPU Inventory
- Making the wallet limited budget

CryptoMining Backend Update

---

src/main/java/com/nighthawk/spring_portfolio/mvc/backups/BackupsController.java
src/main/java/com/nighthawk/spring_portfolio/mvc/backups/ImportsController.java
src/main/java/com/nighthawk/spring_portfolio/mvc/person/Person.java
src/main/java/com/nighthawk/spring_portfolio/mvc/person/PersonApiController.java
src/main/resources/templates/person/person-quiz.html
src/main/resources/templates/person/read.html

Reverts CSA-Coders-2025/CSA_Combined_Backend_Fork#80

Revert "Newloginprofileanalytics"

---

src/main/java/com/nighthawk/spring_portfolio/mvc/person/PersonDetailsService.java

Reverts CSA-Coders-2025/CSA_Combined_Backend_Fork#92

Revert "Student toolkit"

---

README.md

Add MVC picture for the backend person to README

---

src/main/java/com/nighthawk/spring_portfolio/mvc/Slack/CalendarEventService.java
src/main/java/com/nighthawk/spring_portfolio/mvc/assignments/AssignmentSubmission.java
src/main/java/com/nighthawk/spring_portfolio/mvc/assignments/AssignmentSubmissionAPIController.java
src/main/java/com/nighthawk/spring_portfolio/mvc/assignments/AssignmentsApiController.java
src/main/java/com/nighthawk/spring_portfolio/mvc/messages/SaigaiComment.java
src/main/java/com/nighthawk/spring_portfolio/mvc/messages/SaigaiCommentApiController.java
src/main/java/com/nighthawk/spring_portfolio/mvc/messages/SaigaiCommentJpaRepository.java
src/main/java/com/nighthawk/spring_portfolio/mvc/messages/SaigaiMessage.java
src/main/java/com/nighthawk/spring_portfolio/mvc/messages/SaigaiMessageApiController.java
src/main/java/com/nighthawk/spring_portfolio/mvc/messages/SaigaiMessageJpaRepository.java
src/main/resources/templates/bathroom/hallpass.html

Reverts CSA-Coders-2025/CSA_Combined_Backend_Fork#97

Revert "Student Toolkit new features and changes"

---

src/main/java/com/nighthawk/spring_portfolio/mvc/backups/ImportsController.java

Database imports was unable to create new columns in tables and new tables based on the new json file. I just added a feature to creation new columns/tables as needed.

Database Import Bug Fixes

---

src/main/java/com/nighthawk/spring_portfolio/mvc/bathroom/HallPass.java
src/main/java/com/nighthawk/spring_portfolio/mvc/bathroom/HallPassController.java
src/main/java/com/nighthawk/spring_portfolio/mvc/bathroom/HallPassService.java
src/main/java/com/nighthawk/spring_portfolio/mvc/bathroom/Teacher.java

With the changes I made to the files related to hall pass this allows the user to enter which teachers class they are in. I didn't create any new files but modify existing ones. The main things were adding getters and setters then adding the methods so that I can look up teachers in the linked database table.

Added teacher 

---

src/main/java/com/nighthawk/spring_portfolio/mvc/media/MediaApiController.java
src/main/java/com/nighthawk/spring_portfolio/mvc/media/Score.java

synchronized method signature flag to get rid of race condition

Media bias backend final

---

src/main/java/com/nighthawk/spring_portfolio/mvc/backups/ImportsController.java

fixing code where if tables are empty they arent added

---

src/main/java/com/nighthawk/spring_portfolio/mvc/Fibonacci/FibonacciController
src/main/java/com/nighthawk/spring_portfolio/mvc/profileThymeleaf/profileThymeleafApi.java
src/main/java/com/nighthawk/spring_portfolio/mvc/profileThymeleaf/profileThymeleafViewController.java
src/main/resources/templates/layouts/nav.html
src/main/resources/templates/profileThymeleaf.html

-add torin's changes to deployed

Profile thymeleaf

---

src/main/java/com/nighthawk/spring_portfolio/mvc/Slack/SlackService.java
src/main/java/com/nighthawk/spring_portfolio/security/SecurityConfig.java

Quick Fix: Calendar Broken
- Old webhook was deleted causing 404 no connection errors (new webhook added)
- login + Security not working (cookie not being read)

PUSH NOW: security removed + webhook readded

---

src/main/java/com/nighthawk/spring_portfolio/mvc/dataFun/GdpViewController.java
src/main/java/com/nighthawk/spring_portfolio/mvc/person/Person.java
src/main/java/com/nighthawk/spring_portfolio/mvc/person/PersonViewController.java
src/main/java/com/nighthawk/spring_portfolio/mvc/trains/Product.java
src/main/java/com/nighthawk/spring_portfolio/mvc/trains/Train.java
src/main/java/com/nighthawk/spring_portfolio/mvc/trains/TrainCombinedApiController.java
src/main/java/com/nighthawk/spring_portfolio/mvc/trains/TrainCombinedViewController.java
src/main/java/com/nighthawk/spring_portfolio/mvc/trains/TrainCompany.java
src/main/java/com/nighthawk/spring_portfolio/mvc/trains/TrainCompanyJPARepository.java
src/main/java/com/nighthawk/spring_portfolio/mvc/trains/TrainCompanyViewController.java
src/main/java/com/nighthawk/spring_portfolio/mvc/trains/TrainJPARepository.java
src/main/java/com/nighthawk/spring_portfolio/mvc/trains/TrainOrder.java
src/main/java/com/nighthawk/spring_portfolio/mvc/trains/TrainOrderJPARepository.java
src/main/java/com/nighthawk/spring_portfolio/mvc/trains/TrainOrders/MoveOrder.java
src/main/java/com/nighthawk/spring_portfolio/mvc/trains/TrainStation.java
src/main/java/com/nighthawk/spring_portfolio/mvc/trains/TrainStationJPARepository.java
src/main/java/com/nighthawk/spring_portfolio/security/SecurityConfig.java
src/main/resources/static/js/person-verification.js
src/main/resources/static/js/train.js
src/main/resources/templates/data-fun/gdp.html
src/main/resources/templates/login.html
src/main/resources/templates/person/read.html
src/main/resources/templates/person/update-roles.html
src/main/resources/templates/person/update.html
src/main/resources/templates/train/home.html

1. New endpoint for "data-fun", which uses chart.js and a fetch request to world bank indicators database to get information about data in countries around the world.
2. Spinners added to update, update-roles, and login pages, to show that the submission of forms is being processed.
3. I think I finally fixed update-roles, it was broken after new changes to popup update/update-roles pages on the read page
4. improved the look of the login page form
5. hides update roles button when user is not an admin, it already didn't allow non-admins to update roles, but now the button won't even show in the first place.

Trystan - update backend with some ui improvments, added spinners to some of the form submissions

---

src/main/java/com/nighthawk/spring_portfolio/mvc/assignments/AssignmentsApiController.java
src/main/resources/templates/assignments/assignment_tracker.html
src/main/resources/templates/layouts/base.html

Stuff changed
- Fixed student focused submissions page giving an error when you click view submissions
- Removed page title and line on header since it was repetitive

Fixing assignments bugs 

---

src/main/java/com/open/spring/mvc/assignments/AssignmentSubmissionAPIController.java
src/main/java/com/open/spring/mvc/assignments/AssignmentsApiController.java
src/main/resources/templates/assignments/assignment_tracker.html

Changes made
- Fixed assignment date format because it was accidentally changed and messed up calendar
- Minor UI fixes
- Bulk exporting of all assignments
- Exporting of individual assignment
- Exporting of individual assignment submissions

Assignment Fixes and Changes

---

src/main/java/com/open/spring/mvc/assignments/AssignmentSubmissionAPIController.java
src/main/java/com/open/spring/mvc/assignments/AssignmentsApiController.java
src/main/resources/templates/assignments/assignment_tracker.html

Reverts CSA-Coders-2025/CSA_Combined_Backend_Fork#239

Revert "Assignment Fixes and Changes"

---

src/main/java/com/open/spring/mvc/assignments/AssignmentSubmissionAPIController.java
src/main/java/com/open/spring/mvc/assignments/AssignmentsApiController.java
src/main/resources/templates/assignments/assignment_tracker.html

Reverts CSA-Coders-2025/CSA_Combined_Backend_Fork#242

Revert "Revert "Assignment Fixes and Changes""
